# build scene police site
name: Deploy Hugo site 

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
      Deploy:
        runs-on: ubuntu-latest
        steps:
    
        - uses: actions/checkout@v1
          with:
            submodules: true
    
        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: '0.114.0'
            extended: true
    
        - name: Build site
          run: hugo --minify
    
        - name: List output files
          run: ls public
      
        - name: Auth
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'
        
        - name: Deploy
          run: gsutil -m rsync -d -c -r public {{ secrets.GCP_SA_KEY }}gs://scenepolice
         
        - name: Clear HTML Cache
          run: gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://scenepolice/*